#!/usr/bin/env python3
"""
Generate components/ui/icons.tsx from the exported SVGs in public/assets/icons.

External `<use href="...svg">` references are blocked by browsers, so the
glyphs have to be inlined. Hardcoded fills are normalised to currentColor so
each icon can take its colour from the surrounding text (the design uses
text colour to tone icons, e.g. a lime star on a blue hero).

Each viewBox is padded back out to the icon's Figma frame, which the node
render cropped away. Figma draws a glyph as a vector optically inset inside
an instance frame - a 15.91x16 funnel inside a 24x24 slot - and that frame is
what makes every icon in a set read at the same weight. Using the cropped
vector box as the viewBox instead inflates each glyph to fill its box, so a
funnel fills 20px while the 18x12 sort bars beside it render 12px tall.

Run:  python scripts/gen_icons.py
"""

import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
SRC = os.path.join(ROOT, "public", "assets", "icons")
FRAMES = os.path.join(ROOT, ".figma", "icon_frames.json")
OUT = os.path.join(ROOT, "components", "ui", "icons.tsx")

# The exported filenames do not all match the names the code imports. The
# stem is what the export is called; the key is the name components use.
# dot-blank.svg holds the shopping-bag glyph, and the sort-bars and star
# exports are each shared by two colour variants that differ only in the
# fill applied at the call site.
RENAMES = {
    "dot-blank": "shopping-bag",
    "Vector": None,  # a stray export with no call site
}

HEADER = '''// AUTO-GENERATED by scripts/gen_icons.py - do not edit by hand.
// Source: the unique glyph vectors in the ByteSpace Figma file.

import type { SVGProps } from "react";

const P = {
'''

FOOTER = '''};

export const ICON_NAMES = Object.keys(P) as IconNameArray;
export type IconName = keyof typeof P;
type IconNameArray = readonly IconName[];

type IconProps = Omit<SVGProps<SVGSVGElement>, "name"> & {
  name: IconName;
  /** Design sizes are 12 / 16 / 20 / 24 / 32 / 40 / 60. */
  size?: number;
};

/**
 * Every glyph inherits colour from the surrounding text via currentColor, so
 * `className="text-lime"` tints the icon. The inner markup is inlined from
 * the Figma export by scripts/gen_icons.py, never user input.
 */
export function Icon({ name, size = 20, className, ...rest }: IconProps) {
  const { viewBox, body } = P[name];
  return (
    <svg
      width={size}
      height={size}
      viewBox={viewBox}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      className={className}
      dangerouslySetInnerHTML={{ __html: body }}
      {...rest}
    />
  );
}
'''


def clean(raw):
    """Strip the svg wrapper attrs and normalise fills to currentColor."""
    m = re.search(r'viewBox="([^"]+)"', raw)
    view_box = m.group(1) if m else "0 0 20 20"
    inner = re.sub(r"^.*?<svg[^>]*>", "", raw, flags=re.S)
    inner = re.sub(r"</svg>\s*$", "", inner, flags=re.S)
    inner = re.sub(r'fill="(?!none)[^"]*"', 'fill="currentColor"', inner)
    inner = re.sub(r"\s+", " ", inner).strip()
    return view_box, inner


def padded_view_box(view_box, frame):
    """Re-expand a cropped viewBox to the icon's designed frame.

    The vector is centred in the frame exactly as Figma places it. Scaling
    is left to preserveAspectRatio, so a non-square frame still letterboxes
    correctly - what matters is that the glyph's share of the box matches the
    design rather than filling it.
    """
    if not frame:
        return view_box
    _, _, w, h = (float(v) for v in view_box.replace(",", " ").split())
    fw, fh = frame
    if not w or not h:
        return view_box
    dx, dy = (fw - w) / 2.0, (fh - h) / 2.0
    if abs(dx) < 0.01 and abs(dy) < 0.01:
        return view_box
    return "%g %g %g %g" % (-dx, -dy, fw, fh)


def main():
    frames = {}
    if os.path.exists(FRAMES):
        with open(FRAMES, encoding="utf-8") as fh:
            frames = json.load(fh)
    else:
        print("note: no %s, viewBoxes left cropped - run icon_frames.py first"
              % os.path.basename(FRAMES))

    names = sorted(f for f in os.listdir(SRC) if f.endswith(".svg"))
    parts, skipped = [], []
    for name in names:
        stem = name[:-4]
        if stem in RENAMES:
            key = RENAMES[stem]
            if key is None:
                skipped.append(stem)
                continue
        else:
            key = stem
        with open(os.path.join(SRC, name), encoding="utf-8") as fh:
            view_box, body = clean(fh.read())
        view_box = padded_view_box(view_box, frames.get(stem))
        if "'" in body:
            raise SystemExit("%s: body contains a single quote" % stem)
        # JSX cannot hold raw tags in an object literal, so the inner markup is
        # kept as a string and injected via dangerouslySetInnerHTML. Single
        # quotes keep the SVG's own double quotes readable.
        parts.append('  "%s": {\n    viewBox: "%s",\n    body: \'%s\',\n  },\n'
                     % (key, view_box, body))

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER + "".join(parts) + FOOTER)
    print("wrote %s with %d icons" % (OUT, len(parts)))
    if skipped:
        print("  skipped (no call site):", ", ".join(skipped))


if __name__ == "__main__":
    main()
