#!/usr/bin/env python3
"""
Generate components/ui/CategoryIcons.tsx from the six category glyphs in
the Figma file (the tiles in "Frame 10").

These are separate from the 27 unique page icons: they live inside
instance nodes on the category cards and are not reachable from the
generic vector sweep in figma_assets.py, because they are component
instances rather than loose VECTOR nodes.

The file JSON has to be fetched with geometry=paths - the plain /files
response omits vector paths entirely.

Run:  python scripts/gen_category_icons.py
"""

import json
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
OUT = os.path.join(ROOT, "components", "ui", "CategoryIcons.tsx")
CACHE = os.path.join(ROOT, ".figma", "cat_nodes.json")

FILE_KEY = os.environ.get("FIGMA_FILE_KEY", "OfiTDVmxnfjhcKcdLVtk0A")

# node id -> exported name
ICONS = [
    ("11:71", "design"),
    ("12:157", "development"),
    ("12:159", "itSoftware"),
    ("12:166", "business"),
    ("12:162", "marketing"),
    ("12:164", "photography"),
]

HEADER = '''// AUTO-GENERATED by scripts/gen_category_icons.py - do not edit by hand.
// Source: the six category glyphs in the Figma home frame.

import type { SVGProps } from "react";

type Glyph = { viewBox: string; body: string };

const GLYPHS: Record<Name, Glyph> = {
'''

FOOTER = '''};

export const CATEGORY_ICON_NAMES = [
  "design",
  "development",
  "itSoftware",
  "business",
  "marketing",
  "photography",
] as const;

export type CategoryIconName = (typeof CATEGORY_ICON_NAMES)[number];
type Name = CategoryIconName;

type IconProps = Omit<SVGProps<SVGSVGElement>, "name"> & {
  name: CategoryIconName;
  size?: number;
};

/**
 * The category glyphs inherit colour from the surrounding text via
 * currentColor, so `className="text-ink"` tints them.
 */
export function CategoryIcon({ name, size = 36, className, ...rest }: IconProps) {
  const { viewBox, body } = GLYPHS[name];
  return (
    <svg
      width={size}
      height={size}
      viewBox={viewBox}
      fill="currentColor"
      aria-hidden="true"
      focusable="false"
      className={className}
      dangerouslySetInnerHTML={{ __html: body }}
      {...rest}
    />
  );
}
'''


def fetch():
    token = os.environ["FIGMA_TOKEN"]
    url = (
        "https://api.figma.com/v1/files/%s/nodes?ids=%s&geometry=paths&depth=4"
        % (FILE_KEY, ",".join(i for i, _ in ICONS))
    )
    req = urllib.request.Request(url, headers={"X-Figma-Token": token})
    with urllib.request.urlopen(req) as r:
        data = json.load(r)
    with open(CACHE, "w", encoding="utf-8") as fh:
        json.dump(data, fh)
    return data


def matrix_of(node):
    """A node's relativeTransform as an SVG transform string.

    Figma path data is relative to the node's own origin, so without this
    the geometry lands at (0,0) of the parent frame instead of where the
    node sits inside it. The six category glyphs are all centred in their
    36x36 frames by exactly this offset - design sits at (4.5, 4.5),
    itSoftware at (0, 6) - so dropping it throws every glyph up and to
    the left of centre.

    Figma's relativeTransform is [[a, c, e], [b, d, f]] and SVG's matrix()
    takes (a, b, c, d, e, f) over the same column-vector convention, so
    the six values transpose rather than reorder.
    """
    t = node.get("relativeTransform")
    if not t:
        return None
    (a, c, e), (b, d, f) = t[0], t[1]
    values = (a, b, c, d, e, f)
    if values == (1, 0, 0, 1, 0, 0):
        return None  # identity: no wrapper needed
    return "matrix(%s)" % " ".join("%g" % v for v in values)


def geometry_of(node, seen=None):
    """Flatten a node's vector geometry into SVG path elements.

    Each vector is wrapped in a <g> carrying its own transform so nested
    geometry keeps its position within the parent frame.
    """
    if seen is None:
        seen = set()
    parts = []
    for child in node.get("children", []) or []:
        inner = []
        for p in child.get("fillGeometry") or child.get("pathGeometry") or []:
            if p.get("path"):
                inner.append('<path d="%s"/>' % p["path"])
        if child.get("strokeGeometry") and child.get("strokeWeight"):
            w = child["strokeWeight"]
            for p in child["strokeGeometry"]:
                if p.get("path"):
                    inner.append(
                        '<path d="%s" fill="none" stroke="currentColor" '
                        'stroke-width="%s" stroke-linecap="round" '
                        'stroke-linejoin="round"/>' % (p["path"], w)
                    )
        inner.extend(geometry_of(child, seen))
        if not inner:
            continue
        # Figma's boolean ops can leave the same outline on two sibling
        # vectors (design's frame holds the wrench head twice). Painting an
        # identical fill twice is invisible but bloats the markup.
        unique = []
        for el in inner:
            if el in seen:
                continue
            seen.add(el)
            unique.append(el)
        if not unique:
            continue
        transform = matrix_of(child)
        if transform:
            unique = ['<g transform="%s">%s</g>' % (transform, "".join(unique))]
        parts.extend(unique)
    return parts


def main():
    data = fetch() if not os.path.exists(CACHE) else json.load(
        open(CACHE, encoding="utf-8")
    )
    nodes = data["nodes"]

    lines = []
    for node_id, name in ICONS:
        node = nodes[node_id]["document"]
        box = node.get("absoluteBoundingBox") or {}
        w = box.get("width", 36) or 36
        h = box.get("height", 36) or 36
        body = "".join(geometry_of(node))
        if not body:
            raise SystemExit("no geometry for %s (%s)" % (name, node_id))
        lines.append(
            '  %s: { viewBox: "0 0 %g %g", body: %s },'
            % (name, w, h, json.dumps(body))
        )

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n" + FOOTER)
    print("wrote %s with %d icons" % (OUT, len(lines)))


if __name__ == "__main__":
    main()
